fix build after commit 86015fd
sched.h needs to be included, or else gcc throws an error:

drivers/cpufreq/cpufreq.c: In function 'store_scaling_min_freq':
drivers/cpufreq/cpufreq.c:466:185: error: dereferencing pointer to incomplete type 'struct task_struct'

https://stackoverflow.com/questions/10838342/how-does-current-pid-work-for-linux

Signed-off-by: Stefanescu Cristian <howerkraft@gmail.com>